language: php

php:
  - 5.4
  - 5.5
  - 5.6

cache:
  - apt

services:
  - memcached

before_install:
 - composer --prefer-source install
 - composer require phalcon/zephir:dev-master

before_script:
 - ./vendor/bin/zephir generate
 - (cd ext; export CFLAGS="-g3 -O1 -std=gnu90 -Wall -DZEPHIR_RELEASE=1"; phpize && ./configure --enable-phalcon && make --silent -j4 && sudo make --silent install && phpenv config-add ../unit-tests/ci/phalcon.ini)
 - ulimit -c unlimited || true

script: phpunit -c phpunit.xml --coverage-text

notifications:
  email:
    - masdeft@gmail.com