language: php
php:
  - 5.5
  - 5.6
before_install:
  - git clone -q https://github.com/phalcon/cphalcon.git
  - (cd cphalcon/build; sudo ./install && phpenv config-add ./tests/unit/ci/phalcon.ini)
  - composer install
  - ./tests/unit/ci/setup_db.sh
script: phpunit --configuration phpunit.xml
