language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

# optionally set up exclutions and allowed failures in the matrix
matrix:
  exclude:
    - php: hhvm
  allow_failures:
    - php: hhvm

script: phpunit -c phpunit.xml --coverage-text